#!/usr/bin/env python3
"""Choose the committed core corpus from the fetched extended tier.

    tools/corpus/select.py corpus/extended --target 200

Selection is coverage-driven rather than curated by hand. Greedy set cover
first, so every required script, feature class, and encoding trait is present
in as few files as possible; then padding up to the target, preferring small
files and unrepresented scripts.

Why greedy first: it guarantees the invariants verify.py enforces are
satisfiable, and it keeps the committed set small — this is the tier that
lands in every clone and runs on every push. Padding afterwards buys breadth
without letting the set drift toward whatever happened to be downloaded.

Writes corpus/manifest.toml. Copying the files is left to the caller so the
selection can be reviewed before anything is committed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from usfm_features import (  # noqa: E402
    FEATURE_CLASSES, REQUIRED_SCRIPTS, TRAIT_CLASSES,
    detect_features, detect_scripts, detect_traits, read_text,
)

REPO = Path(__file__).resolve().parents[2]


def profile(path: Path) -> dict:
    raw = path.read_bytes()
    text = read_text(path)
    scripts = detect_scripts(text)
    return {
        "path": path,
        "bytes": len(raw),
        "sha256": hashlib.sha256(raw).hexdigest(),
        "scripts": scripts,
        "features": detect_features(text),
        "traits": detect_traits(raw),
        # What this file contributes to the coverage requirement, as opposed to
        # everything it happens to contain.
        "goals": ((scripts & REQUIRED_SCRIPTS)
                  | detect_features(text)
                  | (detect_traits(raw) & TRAIT_CLASSES)),
    }


def greedy_cover(cands: list[dict]) -> list[dict]:
    """Smallest set covering as many goals as the candidates allow."""
    remaining = set(REQUIRED_SCRIPTS) | set(FEATURE_CLASSES) | set(TRAIT_CLASSES)
    chosen: list[dict] = []
    pool = list(cands)

    while remaining:
        # Most new goals per file; ties broken toward smaller files, because
        # this set is committed and cloned forever.
        best = max(pool, key=lambda c: (len(c["goals"] & remaining), -c["bytes"]),
                   default=None)
        if best is None or not (best["goals"] & remaining):
            break                                  # nothing left can help
        chosen.append(best)
        remaining -= best["goals"]
        pool.remove(best)

    if remaining:
        print(f"warning: no candidate covers {', '.join(sorted(remaining))}",
              file=sys.stderr)
    return chosen


def pad(chosen: list[dict], cands: list[dict], target: int) -> list[dict]:
    """Fill to *target*, spreading across scripts and preferring small files."""
    picked = {c["path"] for c in chosen}
    counts: dict[str, int] = {}
    for c in chosen:
        for s in c["scripts"]:
            counts[s] = counts.get(s, 0) + 1

    rest = [c for c in cands if c["path"] not in picked]
    while len(chosen) < target and rest:
        rest.sort(key=lambda c: (min((counts.get(s, 0) for s in c["scripts"]),
                                     default=0), c["bytes"]))
        pick = rest.pop(0)
        chosen.append(pick)
        for s in pick["scripts"]:
            counts[s] = counts.get(s, 0) + 1
    return chosen


def load_provenance(root: Path) -> dict:
    f = root / "provenance.json"
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else {}


def toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def toml_array(values) -> str:
    return "[" + ", ".join(toml_str(v) for v in sorted(values)) + "]"


def write_manifest(chosen: list[dict], prov: dict, root: Path, out: Path) -> None:
    lines = [
        "# Core corpus manifest — generated by tools/corpus/select.py",
        "# Every entry is committed to the repository and runs on every push.",
        "# Regenerate with `just corpus-select`; verify with `just corpus-verify`.",
        "",
    ]
    for c in sorted(chosen, key=lambda c: str(c["path"])):
        rel = c["path"].relative_to(root)
        tid = rel.parts[0] if len(rel.parts) > 1 else ""
        meta = prov.get(tid, {})
        lines += [
            "[[file]]",
            "path = " + toml_str(f"core/{rel.name}"),
            "sha256 = " + toml_str(c["sha256"]),
            f'bytes = {c["bytes"]}',
            "translation = " + toml_str(tid),
            "source = " + toml_str(meta.get("source", "")),
            "language = " + toml_str(meta.get("language", "")),
            "script_declared = " + toml_str(meta.get("script", "")),
            "direction = " + toml_str(meta.get("direction", "")),
            "copyright = " + toml_str(meta.get("copyright", "")),
            "redistributable = " + toml_str(meta.get("redistributable", "")),
            "scripts = " + toml_array(c["scripts"]),
            "features = " + toml_array(c["features"]),
            "traits = " + toml_array(c["traits"]),
            "",
        ]
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", type=Path, help="fetched extended tier")
    ap.add_argument("--target", type=int, default=200)
    ap.add_argument("--manifest", type=Path, default=REPO / "corpus" / "manifest.toml")
    ap.add_argument("--copy-to", type=Path, help="also copy selected files here")
    args = ap.parse_args()

    files = [p for p in sorted(args.source.rglob("*"))
             if p.suffix.lower() in {".usfm", ".sfm"}]
    if not files:
        print(f"no USFM files under {args.source} — run `just corpus-fetch` first",
              file=sys.stderr)
        return 1

    print(f"profiling {len(files)} candidates…", file=sys.stderr)
    cands = [profile(f) for f in files]

    chosen = greedy_cover(cands)
    print(f"greedy cover: {len(chosen)} files", file=sys.stderr)
    chosen = pad(chosen, cands, args.target)
    print(f"after padding: {len(chosen)} files, "
          f"{sum(c['bytes'] for c in chosen)//1024//1024} MB", file=sys.stderr)

    prov = load_provenance(args.source)
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    write_manifest(chosen, prov, args.source, args.manifest)
    print(f"manifest written to {args.manifest}", file=sys.stderr)

    if args.copy_to:
        args.copy_to.mkdir(parents=True, exist_ok=True)
        for c in chosen:
            (args.copy_to / c["path"].name).write_bytes(c["path"].read_bytes())
        print(f"copied {len(chosen)} files to {args.copy_to}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
