#!/usr/bin/env python3
"""Verify the committed core corpus. Runs in CI on every push.

    tools/corpus/verify.py

Checks, in order:

  1. every manifest entry exists on disk
  2. every file hashes to its recorded sha256
  3. no file in corpus/core is missing from the manifest
  4. every entry records provenance and a redistribution decision
  5. the set covers every required script, feature class, and encoding trait

Exits non-zero on any failure. A drifting corpus makes every downstream test
failure ambiguous — did the parser break, or did the input change? — so this
is a hard gate rather than a warning.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from usfm_features import (  # noqa: E402
    FEATURE_CLASSES, REQUIRED_SCRIPTS, TRAIT_CLASSES,
    detect_features, detect_scripts, detect_traits, read_text,
)

REPO = Path(__file__).resolve().parents[2]
CORPUS = REPO / "corpus"

# Python 3.11+ has tomllib; 3.10 does not, and the manifest is generated by us
# in a fixed shape, so a small reader keeps this dependency-free on every runner.
try:
    import tomllib

    def load_manifest(path: Path) -> list[dict]:
        return tomllib.loads(path.read_text(encoding="utf-8")).get("file", [])
except ModuleNotFoundError:
    _KV = re.compile(r'^(\w+)\s*=\s*(.+)$')

    def _value(raw: str):
        raw = raw.strip()
        if raw.startswith("["):
            return [m.group(1) for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', raw)]
        if raw.startswith('"'):
            return raw[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        return int(raw) if raw.isdigit() else raw

    def load_manifest(path: Path) -> list[dict]:
        entries: list[dict] = []
        cur: dict | None = None
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line == "[[file]]":
                cur = {}
                entries.append(cur)
            elif cur is not None and (m := _KV.match(line)):
                cur[m.group(1)] = _value(m.group(2))
        return entries


class Report:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, msg: str) -> None:
        self.errors.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    def finish(self, checked: int) -> int:
        for w in self.warnings:
            print(f"warning: {w}")
        for e in self.errors:
            print(f"error: {e}")
        if self.errors:
            print(f"\nFAIL — {len(self.errors)} error(s) across {checked} files")
            return 1
        print(f"\nOK — {checked} files verified"
              + (f", {len(self.warnings)} warning(s)" if self.warnings else ""))
        return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", type=Path, default=CORPUS)
    ap.add_argument("--manifest", type=Path, default=None)
    ap.add_argument("--skip-coverage", action="store_true",
                    help="check hashes only; used while the corpus is being assembled")
    args = ap.parse_args()

    manifest_path = args.manifest or args.corpus / "manifest.toml"
    core_dir = args.corpus / "core"
    rep = Report()

    if not manifest_path.exists():
        print(f"error: no manifest at {manifest_path}")
        print("run `just corpus-fetch` then `just corpus-select` to build one")
        return 1

    entries = load_manifest(manifest_path)
    if not entries:
        print(f"error: {manifest_path} contains no [[file]] entries")
        return 1

    scripts: set[str] = set()
    features: set[str] = set()
    traits: set[str] = set()
    seen: set[str] = set()

    for e in entries:
        rel = e.get("path")
        if not rel:
            rep.error("manifest entry without a path")
            continue
        seen.add(Path(rel).name)
        path = args.corpus / rel

        if not path.exists():
            rep.error(f"{rel}: listed in the manifest but not on disk")
            continue

        raw = path.read_bytes()
        actual = hashlib.sha256(raw).hexdigest()
        if actual != e.get("sha256"):
            rep.error(f"{rel}: sha256 mismatch\n"
                      f"    expected {e.get('sha256')}\n"
                      f"    actual   {actual}")
            continue

        # 4 — provenance and the redistribution decision must be recorded.
        if not e.get("source"):
            rep.error(f"{rel}: no source URL recorded")
        if not e.get("copyright"):
            rep.warn(f"{rel}: no copyright line recorded")
        if str(e.get("redistributable", "")).strip().lower() != "true":
            rep.error(f"{rel}: redistributable is "
                      f"{e.get('redistributable')!r}, expected \"True\" — "
                      f"this file must not be committed")

        text = read_text(path)
        scripts |= detect_scripts(text)
        features |= detect_features(text)
        traits |= detect_traits(raw)

    # 3 — nothing lurking in core/ that the manifest does not know about.
    if core_dir.exists():
        for f in core_dir.rglob("*"):
            if f.suffix.lower() in {".usfm", ".sfm"} and f.name not in seen:
                rep.error(f"corpus/core/{f.name}: present on disk but not in the manifest")

    # 5 — coverage invariants.
    if not args.skip_coverage:
        for label, missing in (
            ("script", REQUIRED_SCRIPTS - scripts),
            ("feature class", FEATURE_CLASSES - features),
            ("encoding trait", TRAIT_CLASSES - traits),
        ):
            if missing:
                rep.error(f"corpus does not cover {label}(s): {', '.join(sorted(missing))}")

    return rep.finish(len(entries))


if __name__ == "__main__":
    raise SystemExit(main())
