//! The corpus manifest: what is committed, where it came from, and why.

use std::collections::BTreeSet;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Deserialize;

/// One committed corpus file.
///
/// Several fields are parsed but not yet read by anything. They are the
/// manifest's schema rather than dead weight — provenance and the licence
/// audit are the point of the file (ARCHITECTURE §12.4), and dropping a field
/// because no caller reads it today would silently discard the record.
#[allow(dead_code)]
#[derive(Debug, Clone, Deserialize)]
pub struct Entry {
    pub path: String,
    pub sha256: String,
    /// `"vendored"` for a file fetched from a published translation, or
    /// `"authored"` for one written for this repository.
    ///
    /// The distinction is a licence-audit one before it is anything else: a
    /// vendored file must record where it came from and that its terms allow
    /// redistribution, and an authored file has no upstream to record. Defaults
    /// to vendored, so an entry that predates this field keeps its meaning.
    #[serde(default = "vendored")]
    pub origin: String,
    #[serde(default)]
    pub bytes: u64,
    #[serde(default)]
    pub translation: String,
    #[serde(default)]
    pub source: String,
    #[serde(default)]
    pub language: String,
    #[serde(default)]
    pub script_declared: String,
    #[serde(default)]
    pub direction: String,
    #[serde(default)]
    pub copyright: String,
    #[serde(default)]
    pub redistributable: String,
    #[serde(default)]
    pub scripts: Vec<String>,
    #[serde(default)]
    pub features: Vec<String>,
    #[serde(default)]
    pub traits: Vec<String>,
}

fn vendored() -> String {
    "vendored".to_string()
}

#[derive(Debug, Default, Deserialize)]
pub struct Manifest {
    #[serde(default, rename = "file")]
    pub files: Vec<Entry>,
}

pub fn load(path: &Path) -> Result<Manifest> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

/// Written by hand rather than through `toml::to_string` so the header comment
/// survives and the field order stays stable across regenerations — a manifest
/// that reorders itself produces noisy diffs for no reason.
pub fn render(entries: &[RenderEntry]) -> String {
    let mut s = String::new();
    s.push_str("# Core corpus manifest — generated by `cargo xtask corpus select`.\n");
    s.push_str("# Every entry is committed to the repository and runs on every push.\n");
    s.push_str("# Verify with `cargo xtask corpus verify`.\n\n");

    for e in entries {
        s.push_str("[[file]]\n");
        push_str_field(&mut s, "path", &e.path);
        push_str_field(&mut s, "sha256", &e.sha256);
        push_str_field(&mut s, "origin", &e.origin);
        s.push_str(&format!("bytes = {}\n", e.bytes));
        push_str_field(&mut s, "translation", &e.translation);
        push_str_field(&mut s, "source", &e.source);
        push_str_field(&mut s, "language", &e.language);
        push_str_field(&mut s, "script_declared", &e.script_declared);
        push_str_field(&mut s, "direction", &e.direction);
        push_str_field(&mut s, "copyright", &e.copyright);
        push_str_field(&mut s, "redistributable", &e.redistributable);
        push_arr_field(&mut s, "scripts", &e.scripts);
        push_arr_field(&mut s, "features", &e.features);
        push_arr_field(&mut s, "traits", &e.traits);
        s.push('\n');
    }
    s
}

pub struct RenderEntry {
    pub path: String,
    pub sha256: String,
    pub origin: String,
    pub bytes: u64,
    pub translation: String,
    pub source: String,
    pub language: String,
    pub script_declared: String,
    pub direction: String,
    pub copyright: String,
    pub redistributable: String,
    pub scripts: BTreeSet<String>,
    pub features: BTreeSet<String>,
    pub traits: BTreeSet<String>,
}

fn escape(v: &str) -> String {
    v.replace('\\', "\\\\").replace('"', "\\\"")
}

fn push_str_field(s: &mut String, key: &str, value: &str) {
    s.push_str(&format!("{key} = \"{}\"\n", escape(value)));
}

fn push_arr_field(s: &mut String, key: &str, values: &BTreeSet<String>) {
    let inner: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", escape(v)))
        .collect();
    s.push_str(&format!("{key} = [{}]\n", inner.join(", ")));
}
